# Generated by Django 5.2.12 on 2026-04-15 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Estado da Auditoria',
                'verbose_name_plural': 'Estados da Auditoria',
            },
        ),
        migrations.CreateModel(
            name='ControloISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Controlo ISO',
                'verbose_name_plural': 'Controlos ISO',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Organizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('setor', models.CharField(max_length=100)),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Organização',
                'verbose_name_plural': 'Organizações',
            },
        ),
        migrations.CreateModel(
            name='Questao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('dominio_iso', models.CharField(choices=[('Organizacional', 'A.5 Controlos Organizacionais'), ('Pessoas', 'A.6 Controlos de Pessoas'), ('Físico', 'A.7 Controlos Físicos'), ('Tecnológico', 'A.8 Controlos Tecnológicos')], max_length=50, verbose_name='Tema/Domínio ISO')),
                ('referencia_controlo', models.CharField(help_text='Exemplo: A.5.1, A.8.10', max_length=50)),
            ],
            options={
                'verbose_name': 'Questão / Controlo',
                'verbose_name_plural': 'Questões / Controlos',
                'ordering': ['referencia_controlo'],
            },
        ),
        migrations.CreateModel(
            name='RecursoEducativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título do Recurso')),
                ('tipo', models.CharField(choices=[('Documento', 'Documento (PDF, Word)'), ('Vídeo', 'Vídeo (YouTube, Vimeo)'), ('Template', 'Template (Excel, Word)')], default='Documento', max_length=50)),
                ('descricao', models.TextField(verbose_name='Descrição curta')),
                ('icone', models.CharField(default='📄', help_text='Emoji para o cartão', max_length=10)),
                ('capa', models.ImageField(blank=True, help_text='Imagem de capa estilo SafetyCulture', null=True, upload_to='capas_recursos/')),
                ('ficheiro', models.FileField(blank=True, null=True, upload_to='biblioteca_recursos/')),
                ('link_video', models.URLField(blank=True, null=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Recurso Educativo',
                'verbose_name_plural': 'Recursos Educativos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='TipoUtilizador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo de Utilizador',
                'verbose_name_plural': 'Tipos de Utilizador',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('assinatura_base64', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0, help_text='Nota final de conformidade (0-100)')),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.auditoriaestado')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao')),
            ],
            options={
                'verbose_name': 'Auditoria',
                'verbose_name_plural': 'Auditorias',
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_otp', models.CharField(blank=True, max_length=6, null=True)),
                ('objetivo', models.CharField(blank=True, max_length=50, null=True)),
                ('empresa_default', models.CharField(blank=True, max_length=150, null=True)),
                ('telemovel', models.CharField(blank=True, max_length=20, null=True)),
                ('dois_fatores_ativo', models.BooleanField(default=False)),
                ('totp_secret', models.CharField(blank=True, max_length=32, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PerguntaAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto_pergunta', models.CharField(help_text='A pergunta de Sim/Não. Ex: O disco está encriptado?', max_length=255)),
                ('controlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perguntas_praticas', to='core.questao')),
            ],
            options={
                'verbose_name': 'Pergunta Prática',
                'verbose_name_plural': 'Perguntas Práticas',
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('resumo', models.TextField()),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.auditoria')),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
            },
        ),
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.CharField(max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='evidencias_auditoria/')),
                ('auditoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.auditoria')),
                ('pergunta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.perguntaauditoria')),
            ],
            options={
                'verbose_name': 'Resposta',
                'verbose_name_plural': 'Respostas',
            },
        ),
        migrations.CreateModel(
            name='RespostaClienteSoA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplicavel', models.BooleanField(default=True)),
                ('estado', models.CharField(max_length=50)),
                ('justificacao', models.TextField(blank=True, null=True)),
                ('evidencia', models.CharField(blank=True, max_length=255, null=True)),
                ('ultima_atualizacao', models.DateTimeField(auto_now=True)),
                ('controlo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.controloiso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Resposta SoA do Cliente',
                'verbose_name_plural': 'Respostas SoA dos Clientes',
            },
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('nivel', models.CharField(choices=[('Alto', 'Alto'), ('Médio', 'Médio'), ('Baixo', 'Baixo')], max_length=10)),
                ('data_detecao', models.DateField(auto_now_add=True)),
                ('controlo_associado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.controloiso')),
                ('organizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.organizacao')),
            ],
            options={
                'verbose_name': 'Risco',
                'verbose_name_plural': 'Riscos',
            },
        ),
        migrations.CreateModel(
            name='AcaoCorretiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em curso', 'Em curso'), ('Concluída', 'Concluída')], default='Pendente', max_length=20)),
                ('data_limite', models.DateField()),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='core.risco')),
            ],
            options={
                'verbose_name': 'Ação Corretiva',
                'verbose_name_plural': 'Ações Corretivas',
            },
        ),
        migrations.CreateModel(
            name='ProgressoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], default='Pendente', max_length=20)),
                ('data_interacao', models.DateTimeField(auto_now=True)),
                ('utilizador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meus_progressos', to=settings.AUTH_USER_MODEL)),
                ('recurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.recursoeducativo')),
            ],
            options={
                'verbose_name': 'Progresso de Recurso',
                'verbose_name_plural': 'Progressos de Recursos',
                'unique_together': {('utilizador', 'recurso')},
            },
        ),
    ]
