# Generated by Django 5.2.12 on 2026-04-22 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='risco',
            name='auditoria_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.auditoria'),
        ),
        migrations.AddField(
            model_name='risco',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
