# Generated by Django 5.2.12 on 2026-04-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_risco_auditoria_origem_risco_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='perguntaauditoria',
            name='nivel_risco_sugerido',
            field=models.CharField(choices=[('Crítico', 'Crítico'), ('Alto', 'Alto'), ('Médio', 'Médio'), ('Baixo', 'Baixo')], default='Médio', help_text='Se o auditor responder NÃO, qual é a gravidade deste risco?', max_length=10),
        ),
        migrations.AlterField(
            model_name='perguntaauditoria',
            name='texto_pergunta',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='risco',
            name='nivel',
            field=models.CharField(choices=[('Crítico', 'Crítico'), ('Alto', 'Alto'), ('Médio', 'Médio'), ('Baixo', 'Baixo')], max_length=10),
        ),
    ]
