# Generated by Django 5.2.12 on 2026-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_perguntaauditoria_nivel_risco_sugerido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='acaocorretiva',
            name='responsavel',
            field=models.CharField(default='Não atribuído', max_length=150),
        ),
    ]
