# Generated by Django 5.2.12 on 2026-04-23 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_acaocorretiva_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='risco',
            name='evidencia_resolucao',
            field=models.FileField(blank=True, null=True, upload_to='evidencias_acoes/'),
        ),
    ]
